#!/usr/bin/env ruby

require 'net/http'
require 'uri'

SERVER_URI = "http://morishinzo.morishin.me/upload"

# capture png file
tmpfile = "/tmp/image_upload#{$$}.png"
accessToken = ARGV[0]
imagefile = ARGV[1]

if imagefile && File.exist?(imagefile) then
    system "sips -s format png \"#{imagefile}\" --out \"#{tmpfile}\""
else
    system "screencapture -i \"#{tmpfile}\""
    if File.exist?(tmpfile) then
        system "sips -d profile --deleteColorManagementProperties \"#{tmpfile}\""
        dpiWidth    = `sips -g dpiWidth "#{tmpfile}" | awk '/:/ {print $2}'`
        dpiHeight   = `sips -g dpiHeight "#{tmpfile}" | awk '/:/ {print $2}'`
        pixelWidth  = `sips -g pixelWidth "#{tmpfile}" | awk '/:/ {print $2}'`
        pixelHeight = `sips -g pixelHeight "#{tmpfile}" | awk '/:/ {print $2}'`
        if (dpiWidth.to_f > 72.0 and dpiHeight.to_f > 72.0) then
            width  =  pixelWidth.to_f * 72.0 / dpiWidth.to_f
            height =  pixelHeight.to_f* 72.0 / dpiHeight.to_f
            system "sips -s dpiWidth 72 -s dpiHeight 72 -z #{height} #{width} \"#{tmpfile}\""
        end
    end
end

if !File.exist?(tmpfile) then
    exit
end

imagedata = File.read(tmpfile)
File.delete(tmpfile)

boundary = '----BOUNDARYBOUNDARY----'

data = <<EOF
--#{boundary}\r
content-disposition: form-data; name="imagedata"; filename="gyazo.com"\r
\r
#{imagedata}\r
--#{boundary}--\r
EOF

header = {
    'Content-Length' => data.length.to_s,
    'Content-type' => "multipart/form-data; boundary=#{boundary}",
    'Authorization' => "Bearer #{accessToken}"
}

uri = URI.parse(SERVER_URI)

Net::HTTP.start(uri.host, uri.port){|http|
    res = http.post(uri.path, data, header)
    url = res.response.body
    IO.popen("pbcopy","r+"){|io|
        io.write url
        io.close
    }
    system "open #{url}"
}